CREATE PROCEDURE ASSERT @P_Assertion BIT, @TEST_TYPE text, @TEST_NAME text,@ACTUAL_RESULT text,@EXPECTED_RESULT text, @P_ERROR_MESSAGE text
AS
BEGIN
	IF @P_Assertion=0
	EXECUTE Log_result @TEST_TYPE,@TEST_NAME,'FAIL','',@EXPECTED_RESULT,@P_ERROR_MESSAGE
	IF @P_Assertion=1
	EXECUTE Log_result @TEST_TYPE,@TEST_NAME,'PASS',@ACTUAL_RESULT,@EXPECTED_RESULT,''

END
GO